Repository kalviumcommunity/S76_Vignesh_Capstone_Myvote, pull requests merged in 2025-05, with the labels that each got.

#33 dbconnection
  server/database/dbConnection.js
Labels: Review effort 1/5

#34 file upload functionality
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/assets/images/butterfly.gif
  client/src/assets/images/nature.gif
  client/src/pages/NewElection.jsx
  client/src/pages/Vote.jsx
  server/middleware/upload.js
  server/model/electionSchema.js
  server/package-lock.json
  server/package.json
  server/routes/adminDashRoutes.js
  server/routes/electionRoutes.js
  server/server.js
Labels: Review effort 3/5

#38 Election Page
  client/src/App.jsx
  client/src/pages/Elections.jsx
  client/src/routes/Routes.js
Labels: Review effort 2/5

#40 code updation
  server/.gitignore
  server/config/cloudinary.js
Labels: Review effort 1/5
